CC  = clang
CPP = clang
AS  = clang
LD  = ld
AR	= ar

CONFIG_OPTIMIZATION = -O0
CONFIG_TARGET = -m32 -mno-sse -mno-mmx

CONFIG_BUILD_LIBS =
CONFIG_EXCLUDE_FOLDERS = ! -path "*/arm/*"

PERSONALITY = 1
BOOTLOADER = 1
