CC  = gcc
CPP = g++
AS  = gcc
LD  = ld
AR	= ar

CONFIG_OPTIMIZATION = -O0
CONFIG_TARGET = -m32 -mno-sse -mno-mmx

CONFIG_BUILD_LIBS =
CONFIG_EXCLUDE_FOLDERS = ! -path "*/x86/*"

LIBGCC = -L "/home/justsid/opt/cross/lib/gcc/arm-none-eabi/4.8.3/" -lgcc

PERSONALITY = 1
