ASFLAGS  = -m32 -I. -I../.
CFLAGS	 = -m32 -std=c99 -Wall -Wextra -Wno-overloaded-virtual -pedantic -O2 -fpic -fno-stack-protector -fno-builtin -nostdinc -nostdlib -I. -I../.
CPPFLAGS = -m32 -std=c++11 -Wall -Wextra -Wno-overloaded-virtual -pedantic -O2 -fpic -fno-stack-protector -fno-builtin -fno-rtti -fno-exceptions -nostdinc -nostdlib -I. -I../.
LDFLAGS  = -shared