CFLAGS	 = -m32 -Wall -Wextra -pedantic -std=c99 -O2 -fno-stack-protector -fno-builtin -nostdinc -nostdlib -I../../Libraries/.
CPPFLAGS = -m32 -Wall -Wextra -pedantic -std=c++0x -O2 -fno-stack-protector -fno-rtti -fno-exceptions -nostdinc -nostdlib -I../../Libraries/.
LDFLAGS  = -melf_i386